- configs/container.config
- configs/local.config
- configs/nodes.config
- modules/nanoplot.nf
- poreCov.nf
fixes #12 for now. We can open then another issue to implement a summary report so that one does not have to look at each single Nanoplot file (e.g. when running 100 samples...)
> add nanoplot simple read qc

- bin/json_parser.sh
- "ACGT_Identity(_ignoring_Ns)" only written to output if "RKI_Valid" == true
- "RKI_Valid" now transformed to lowercase for uniform appearance
- Fixed quotation
> fixed quotation & added if-exclusion in json_parser

- bin/json_parser.sh
- bin/rki_report_parser.sh
- configs/container.config
- nextflow.config
- poreCov.nf
- workflows/process/download_database_kraken2.nf
- workflows/process/president.nf
- workflows/process/rki_report.nf
* update president v0.4.0
* update krakendb
> up president, krakendb

- bin/split_fasta.py
- modules/split_fasta.nf
- poreCov.nf
- handle multifasta input, should even handle multiple multifastas
- make all sample names and filenames consistent
adds
- bin/split_fasta.py
- module/split_fasta.nf
tests that worked:
- single sequence fasta
- multi fasta
- test_fasta profile
> Add multifasta support

- bin/summary_report.py
- changed using fixed column positions to using column names to get the sample names (should now be robust against more columns being added to any tool, as long as column names don't change
> Fixes summary report for new president version

- bin/summary_report.py
- modules/plot_coverages.nf
- workflows/create_summary_report.nf
- workflows/process/summary_report.nf
- will retain visibility for many samples
- sorted
> Collate coverage plots to groups of 6 samples

- bin/summary_report.py
- configs/container.config
- modules/split_fasta.nf
- check if nextclade did not write any mutations in the column, write '-' if so
> Fix empty mutations + new fastdov version

- bin/summary_report.py
- add absolute read numbers from kraken in a readable format (closes https://github.com/replikation/poreCov/issues/62)
- re-add percentage of Ns (closes https://github.com/replikation/poreCov/issues/66)
- add nextclade aaDeletions column (closes https://github.com/replikation/poreCov/issues/65) (Note there is no aaInsertions column: https://github.com/nextstrain/nextclade/issues/319)
- many format tweaks
-------
-------
> Report updates

- bin/summary_report.py
Important bugfix, row swaps were possible
> bugfix for row swap, safe column adding

- bin/summary_report.py
- workflows/process/summary_report.nf
fixes #71 
suggestions for the color thresholds? right now it is:
%SARS-CoV-2
- \>=95 green
- \>=90 yellow
- \<90 red
%human
- \<=1 green
- \<=5 yellow
- \>5 red
> Include unclassified in kraken2 stats

- bin/json_parser.sh
- configs/container.config
* added new president version
* major change: order of output cols in report
* fixed the JSON shell script accordingly
Worked in my tests. 
Will close #72
> Update president #72

- bin/summary_report.py
- added prominent first line that tells you if all samples passed QC
- shorter column names
- forced linebreaks when fields contain multiple items
- added minimap and fastcov versions
-----------
-----------
> Report style tweaks

- workflows/process/summary_report.nf
- fallbacks were bugged, fixed and improved
> fixed kreport aggregation

- configs/nodes.config
- workflows/process/guppy.nf
* incresed RAM for pycoqc
* restructured some guppy code based on input flags
> Local cloud

- workflows/provide_rki.nf
* also store final FASTAs that also passed QC as singletons for further processing
> store singletons that passed qc

- configs/container.config
* update pangolin to version 2.3.4
> up pangolin

- nextflow.config
- poreCov.nf
- workflows/artic_nanopore_nCov19.nf
- workflows/basecalling.nf
- workflows/process/artic.nf
* implements nanopolish #87  as an option (default is still medaka)
* super slow (7x medaka speed) - not sure if anyone wants to use it
* added #89 suggestion but not as a warning more of a general info
* its a "info print" showing the latest release found on the repo
> Nanopolish implement

- bin/summary_report.py
- poreCov.nf
- workflows/create_summary_report.nf
- workflows/process/summary_report.nf
- adds missing samples to report table and datatables (fixes #92)
- forgot to make a new branch :<
> Add all samples from samples.csv to report table

- poreCov.nf
- workflows/process/artic.nf
- workflows/process/guppy.nf
* @iferres @hoelzer  for modifying parameters and testing
* otherwise i use the most recent artic release implementation
* i increase the normalization maybe the additional information already helps
* should also look into the filtering of reads. might be better to use `artic guppyplex --directory ` with additional quality filtering (see https://artic.readthedocs.io/en/latest/commands/)
> Parameter optimization

- nextflow.config
- poreCov.nf
- workflows/process/collect_fastq.nf
- workflows/process/guppy.nf
Thought about possibility of adding other barcode-kits, but looking through them no others looked really relevant. Only one I missed in nanozoo/guppy-container was the guppy .cfg-file for the 96-rapid barcoding kit. Couldn´t find information about this file so far either.
> Guppy sequ kit

- nextflow.config
- poreCov.nf
- workflows/process/filter_fastq_by_length.nf
- workflows/process/guppy.nf
> V1200 read length parameter & guppy update

- bin/json_parser.py
Closes #124 "Add deletions to json-output"
> Add del to json

- .github/workflows/DryRun.yml
- .github/workflows/nextflow-test.yml
- modules/align_to_reference.nf
- modules/plot_coverages.nf
- modules/split_fasta.nf
- nextflow.config
- poreCov.nf
- workflows/process/artic.nf
- workflows/process/collect_fastq.nf
- workflows/process/covarplot.nf
- workflows/process/download_database_kraken2.nf
- workflows/process/filter_fastq_by_length.nf
- workflows/process/guppy.nf
- workflows/process/json_report.nf
- workflows/process/kraken2.nf
- workflows/process/krona.nf
- workflows/process/nanoplot.nf
- workflows/process/nextclade.nf
- workflows/process/pangolin.nf
- workflows/process/president.nf
- workflows/process/pycoqc.nf
- workflows/process/quality_genome_filter.nf
- workflows/process/rki_report.nf
- workflows/process/seqrs.nf
- workflows/process/summary_report.nf
* dry run tests on `--fasta` and `--fastq`
> stub dryrun tests

- configs/container.config
* changing the underlying alpine OS in nextclade to Debian to avoid singularity permission issues on a cluster:
* fixes #132
> change nextclades base OS

- configs/container.config
@iferres 
* added another container
* i currently don't have compressed fast5 data available to test this.
* could you confirm that it works?
`nextflow pull replikation/poreCov && nextflow run replikation/poreCov -b fix137 --nanopolish (...)`
* conda installation took 2 or 3 days until the env was "resolved"  ...
> changed artic container

- poreCov.nf
- workflows/process/filter_fastq_by_length.nf
adjust default settings for read filtering for --rapid option
> set min length to 100 for rapid

- bin/summary_report.py
- workflows/process/summary_report.nf
Implements #195 
- always shows full poreCov command
- will still try to give a meaningful 'Run type' description
- changed Fonts around because it looked ugly on my Firefox on windows
@hoelzer please test the nanopolish case with fastq/fast5
> Report commandline

- configs/container.config
- configs/local.config
- configs/nodes.config
- nextflow.config
- poreCov.nf
- workflows/process/download_database_kraken2.nf
- workflows/process/krona.nf
- workflows/process/lcs_sc2.nf
- workflows/read_classification.nf
* determine lineages by reads (for mixed samples)
> init LCS pooled sample implementation

- bin/lcs_bar_plot.R
- nextflow.config
- poreCov.nf
- workflows/create_summary_report.nf
- workflows/process/lcs_sc2.nf
- workflows/read_classification.nf
- LCS results for each sample are collected and written to one file
- adds bar plot with all samples
> added bar plot for LCS

- bin/summary_report.py
- modules/plot_coverages.nf
> [Feature] more info on Ns

- nextflow.config
- retry maximal once instead of ignoring
- fixes #263
> changed the error strategy in slurm profile

- README.md
- modules/filter_fastq_by_length.nf
- fixed the if statment to disable filesize filer with csv input
- updated readme removing the `--list` reference
> Fix: disable filesize filer with csv input
