replikation/poreCov

- nextflow.config
Currently, `nextflow.config` points to `nCov.nf` as the main script, so that `nextflow pull...` is not working. It should be `poreCov.nf` (or even better `main.nf`).
> change nextflow.config to correctly point to main script

- workflows/process/bwa_samtools.nf
- add -t ${task.cpus} to bwa mem call
- is much faster now obviously
should think about replacing bwa mem with minimap2 anyway
> Multithreaded bwa mem

- bin/summary_report.py
- workflows/process/summary_report.nf
- force dtype string in all table indexes
- also removed # from header line in kraken aggregate file for robust column selection
tidbits:
the dtype='xx' parameter is actually ineffectual because they get overwritten in the index constructor .... (https://github.com/pandas-dev/pandas/issues/9435)
> Fixes error with only integer-like sample names

- bin/summary_report.py
- configs/container.config
- workflows/process/summary_report.nf
- implements #88
- always adds a .csv and a .xlsx data table to the poreCov output
- columns:
sample | kraken2_numreads_sarscov2 | kraken2_numreads_human | kraken2_numreads_unclassified | kraken2_numreads_total | president_identity | president_mismatches | president_percentN | president_numN | president_QC_pass | pangolin_lineage | pangolin_probability | nextclade_clade | nextclade_mutations | nextclade_deletions
- sample:
[poreCov_summary_report_2021-03-26--16-25-44_datatable.xlsx](https://github.com/replikation/poreCov/files/6212762/poreCov_summary_report_2021-03-26--16-25-44_datatable.xlsx)
- new fastcov container (added openpyxl package)
> Add raw data table output

- nextflow.config
- poreCov.nf
- workflows/artic_nanopore_nCov19.nf
- workflows/process/artic.nf
- workflows/process/collect_fastq.nf
* closes #94
* sequencing summary is provided via `--nanopolish` and it is only necessary if `--fastq` or `--fastq_pass` is provided
* did some small test runs and works fine
* added more verbose error codes throughout the workflow
* needs some proper testing to validate if all workflows are chosen correctly
* @iferres would be glad if you could do some testing
```bash
nextflow pull replikation/poreCov
nextflow run replikation/poreCov  -r no_basecall_nanopolish --fast5 fast5_dir/ --fastq_pass fastq_pass/ --nanopolish sequencing_summary.txt 
```
> nanopolish wo basecalling, improv errorhandling

- bin/split_fasta.py
Overhauled duplicate handling in split_fasta.py to handle multi-fastas where the same sequence(-name) appears multiple times.
sname & ncount-route of the if-statement wasn´t properly working for my test-file.
Also all appearances of a sequence after the first would be melted down into a single second entry, which then was handed over to following processes. E.g.: a multifasta with 4 times the same sequence-name ('>sampleX') would only create two follow-processes ('sampleX' & 'sampleX_02') instead of one per appearance.
> Split fasta improvment

- configs/container.config
* updated the ARTIC container to also include all available models for medaka directly
* thus, no internet connection is needed to pull non-default medaka models and all is in the container already
Tested on cluster machine that is behind a firewall, worked
```
nextflow run poreCov/poreCov.nf -profile local,singularity -params-file run.yml -w work --update --medaka_model r941_min_high_g360 --guppy_model dna_r9.4.1_450bps_sup.cfg --output results_sup_hac -resume
```
suggestion to do a v0.10.1 release then
> update medaka models

- README.md
- bin/summary_report.py
- poreCov.nf
- workflows/create_summary_report.nf
- workflows/process/summary_report.nf
Fixes #136
(and half of #142)
Report now includes:
- Guppy model if basecalling from fast5
- Medaka model if ARTIC is run (just realised that this is misleading/wrong if using nanopolish)
- If providing a samples.csv: If a column is named exactly 'Description', it is added to the output tables (this could be extended to others, or allow selection of the columns via parameters)
> Add guppy/medaka models, print out 'Description' column

- workflows/process/artic.nf
It seems no one was using `nanopolish` for a while ;) 
The output channel for the coverage depth files needed adjustment, similar to the default `medaka` process a while ago. The files were renamed in some ARTIC update. 
Works for me, just did a run with `nanopolish`. So ready to merge and doing a minor release from my side.
> fix output channel for nanopolish

- workflows/process/guppy.nf
I had to adjust some parameters to get Guppy running on an HPC cluster node via SLURM and with URL restrictions but I think this is generally useful for executing poreCov w/ basecalling on SLURM
1) use `--disable_pings` for the guppy commands to just not send information to ONT ;) 
2) add clusterOptions for SLURM to give the basecalling process enough time (otherwise the job might be killed depending on the SLURM configuration)
> Guppy adjustments for HPC (SLURM) execution

- bin/convert_insertions_nt2aa.py
Quick fix for #184
I assume the pos is now the start of the amino acid before the insertion (e.g. R for R214REPE instead of E)
Should give correct amino acid and codon number now
Please test, I can't right now =)
> nextclade pos is now the nucleotide before the insertion

- configs/container.config
Updated Medaka to version 1.5.0 inside the ARTIC workflow (container). Before, the version was 1.4.3
This was an attempt to fix an issue w/ BA.1 and a Deletion causing a frameshift - but this did not help. However, might be not bad to update Medaka at some time.
> bump Medaka version in ARTIC container

- bin/summary_report.py
Trying to improve table readability (implements #207)
- Mutations are now toggled, hidden by default
- font size is smaller in main table
- random tweaks to colnames, linebreaks, etc
Play with it here:
[poreCov_summary_report_2022-02-08--15-07-12.zip](https://github.com/replikation/poreCov/files/8024463/poreCov_summary_report_2022-02-08--15-07-12.zip)
> Table style updates

- bin/lcs_bar_plot.R
- workflows/create_summary_report.nf
- workflows/process/lcs_sc2.nf
The barplot is now split into a single one for the control sample and the rest.
A lot of variants seem to be detected in the control, which messes up the readability for the rest.
> Split LCS barplot

- bin/lcs_bar_plot.R
- configs/container.config
- configs/nodes.config
- nextflow.config
- poreCov.nf
- workflows/create_summary_report.nf
- workflows/process/lcs_sc2.nf
- workflows/read_classification.nf
Adds the functionality to generate an updated UCSC marker table via:
```
--lcs_ucsc_version       Create marker table based on a specific UCSC SARS-CoV-2 tree (e.g. '2022-05-01'). Use 'predefined' 
to use the marker table from the repo (most probably not up-to-date) [default: predefined]
See https://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2 for available trees.
--lcs_ucsc_predefined    If '--lcs_ucsc_version 'predefined'', select pre-calculated UCSC table [default: 2022-01-31]
See https://github.com/rki-mf1/LCS/tree/master/data/pre-generated-marker-tables
--lcs_ucsc_update        Use latest UCSC SARS-CoV-2 tree for marker table update. Overwrites --lcs_ucsc_version [default: false]
Automatically checks https://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/pu …
```
> LCS UCSC marker update feature

- workflows/process/artic.nf
The VCF file (output of artic workflow) is now published to the `lineagedir` (#232 )
A small test on my side looks fine
> publish vcf file, fixes #232

- nextflow.config
- poreCov.nf
- workflows/process/pangolin.nf
- for now the default is that `scorpio` is not skipped and can be skipped with `pangolin_skip_scorpio`
> added skip-scorpio parameter fixes #234

- nextflow.config
- workflows/process/lcs_sc2.nf
- bumped predefined LCS table to 2023-01-26
- introduced tags for LCS repo cloning
> bumped predefined LCS table to 2023-01-26

- configs/container.config
Solves #247 
WIP - tests need to be run.
> Update medaka in artic

- workflows/process/artic.nf
- publishes the following documents for each sample
- `primersitereport.txt` -> variants in primer binding sites
- `coverage_mask.txt` -> low coverage regions
- `fail.vcf` -> filtered and failed variants that get masked with Ns
- solves #245
> [Enhancment] publish more logs/intermediate files from ARTIC

- nextflow.config
- poreCov.nf
- workflows/artic_nanopore_nCov19.nf
- workflows/process/artic.nf
- sets the normalize parameter for the artic minion workflow
- default value is 500; thus default behavior does not change
> [Feature] added parameter artic_normalize

- workflows/process/artic.nf
If the disabling was activated in the pipeline (`--artic_normalize False`), no parameter was handed over to the artic pipeline, so that artic used the default value of 200. Normalisation is now correctly turned off by passing `--normalise 0` to the artic pipeline.
> fixed disabling of artic normalisation

- nextflow.config
- poreCov.nf
bump to latest containers:
- nanozoo/pangolin-v4:4.3--1.25.1
- nanozoo/nextclade3:3.2.1--2024-02-16
> bump default container version for pangolin and nextclade

- configs/container.config
- configs/local.config
- configs/nodes.config
- nextflow.config
- poreCov.nf
- workflows/artic_nanopore_nCov19.nf
- workflows/basecalling.nf
- workflows/create_summary_report.nf
- workflows/process/freyja.nf
- workflows/process/lcs_sc2.nf
- workflows/read_classification.nf
Integration of Freyja for metagenomic screening of reads.
Includes also a restructuring of the LCS-tool for metagenomic read-analysis.
> Freyja integration

- bin/summary_report.py
- based on nextclade `missing` output
- empty if nextclade output empty
- HTML report untouched
> added `nextclade_percentN_spike` column to datatables

- poreCov.nf
freyja expects a trimmed bam file, else mixed variants in primer regions mess up the lineage abundance estimation
> using the primer-trimmed bam file as input for freyja

- README.md
- modules/filter_fastq_by_length.nf
- poreCov.nf
Hi folks,
We have been using `--fastq_pass --samples` as input configuration, but we will switch to `--fastq --list` at some point. While testing, I noticed that the negative control didn't appear in the reports.
Now, I'm not sure if I understand the reasoning behind these lines completely: https://github.com/replikation/poreCov/blob/master/modules/filter_fastq_by_length.nf#L34-L36
However, we'd still like to have the negative control in the report, so with this PR, the removal of small fastq.gz files after the length filter is skipped with `--list` or `--sample`.
> skip removing small fastq.gz files after the length filter with --list or --sample

- lib/Git_PoreCov.groovy
- poreCov.nf
Hi there, 
it's me again, again with the [same line](https://github.com/replikation/poreCov/blob/master/poreCov.nf#L50) and I can't explain why and how.
With Nextflow `24.10.4`, I get, sometimes, not always, a json/text returned that has spaces between the key-value pairs. This leads to an index out of bounds error, because the splitting does not work as expected.
```
Pulling replikation/poreCov ...
Launching `https://github.com/replikation/poreCov` [sleepy_fourier] DSL2 - revision: aa377dc669 [1.12.2]
________________________________________________________________________________
poreCov | A Nextflow SARS-CoV-2 workflow for nanopore data
ERROR ~ Index 1 out of bounds for length 1
-- Check script '<myhome>/replikation/poreCov/poreCov.nf' at line: 50 or see '<foo>/poreCov.nextflow.log' …
```
> Change get porcov version
